### ISSUE TITLE
Integrate / Hook up with HTML Webpack Plugin

### ISSUE THREAD

**Issue by csentis** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#1]
Hi @jouni-kantola, thank for this plugin which in my eyes is the leanest approach to the very specific use case it covers.

I had originally tried to cover inlining the chunks manifest by means of HTML Webpack  Plugin (or plugins advertised as using its hooks).

Makes me wonder whether you might not want to get in touch with the author of HTML Webpack Plugin as he has offered here: jantimon/html-webpack-plugin#600. Could be an idea to have your plugin listed in his README or find better ways to further integrate your solution.

**Comment by jouni-kantola** [comment]
I'm glad it comes to use 👍  Thank you for the feedback! Since you mentioned this, I decided to publish the plugin to npm (https://www.npmjs.com/package/inline-chunk-manifest-html-webpack-plugin). Readme is updated accordingly.

I'll update the issue you referenced as well.

Out of interest, how did you find the plugin?

**Comment by csentis** [comment]
Pretty straightforward - and, with it, simply good and mighty useful. You enabled me to reflect a custom chunks manifest config in webpack.conf.js:
```
new InlineChunkManifestHtmlWebpackPlugin({
        filename: 'abcdef-chunks-manifest.json',
        manifestVariable: 'abcdefChunksManifest'
}),
```

... whilst using Chunks Manifest Plugin of course in this way:

```
new ChunkManifestPlugin({
        filename: 'midyll-chunks-manifest.json',
        manifestVariable: 'midyllChunksManifest'
}),
```

Thank you - also for making it available via npm!

**Comment by jouni-kantola** [comment]
Closing this, and I'll see what the issue you linked ends up with.

**Comment by jouni-kantola** [comment]
@csentis: Now I feel the plugin has matured enough to link from `html-webpack-plugin`'s readme. Here's the PR:
https://github.com/jantimon/html-webpack-plugin/pull/647

Is the plugin still working well for you? I'm keeping my fingers crossed that `v1.1.0` will be a stable one for quite some time.

I wanted to reach out again since you were the one who actually triggered life into this plugin 😄

**Comment by csentis** [comment]
@jouni-kantola Sorry I had not seen this before. Kind of drowning ;-)

Plugin works just fine and I am very happy that you deliberately picked up my initial suggestion. Glad if I was able to support this awfully useful and good work of yours!
